service: api-verificacao-senha-studio-sol # nome do serviço na AWS

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1 # região onde a função será implantada
  stage: prod # ambiente de implantação (ex: dev, staging, prod)

functions:
  app:
    handler: app.handler # caminho para o arquivo que contém o código da função
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /verify
          method: POST